<?php


function importstaff_permission() {
  return array(
    'administer importstaff' => array(
      'title' => t('administor_importstaff'),
      'description' => t('Perform administration tasks for importstaff.'),
    ),
  );
}

function importstaff_menu() {
  $items['admin/config/importstaff'] = array(
    'title' => 'Example Page of cron',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('importstaff_admin_form'),
    'access arguments' => array('administer importstaff'),
    'type' => MENU_NORMAL_ITEM,
  );
 

  return $items;
}


function importstaff_admin_form($form, &$form_state) {


$form['importstaff_enable'] = array(
  '#type' => 'textfield',
  '#title' => t('Subject'),
  '#size' => 60,
  '#maxlength' => 128,
  '#required' => TRUE,
  '#default_value'  => variable_get ('importstaff_enable',"ret@yahoo.com"),
);
return system_settings_form($form);
}