<?php


function cronmonitor_permission() {
  return array(
    'administer cronmonitor' => array(
      'title' => t('administor_cronmonitor'),
      'description' => t('Perform administration tasks for cronmonitor.'),
    ),
  );
}

function cronmonitor_menu() {
  $items['admin/config/cronmonitor'] = array(
    'title' => 'Example Page of cron',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cronmonitor_admin_form'),
    'access arguments' => array('administer cronmonitor'),
    'type' => MENU_NORMAL_ITEM,
  );
 

  return $items;
}


function cronmonitor_admin_form($form, &$form_state) {


$form['cronmonitor_enable'] = array(
  '#type' => 'textfield',
  '#title' => t('Subject'),
  '#size' => 60,
  '#maxlength' => 128,
  '#required' => TRUE,
  '#default_value'  => variable_get ('cronmonitor_enable',"ret@yahoo.com"),
);
return system_settings_form($form);
}